version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=your_money_or_your_light_development
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - "5432"
  web:
    build: .
    container_name: your-money-or-your-light-web
    ports:
      - "3010:3000"
    depends_on:
      - db
    volumes:
      - .:/your-money-or-your-light
volumes:
  db: